runtime: nodejs
env: flex
instance_class: F1
automatic_scaling:
  min_num_instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /api/.*
    script: app.js
  - url: /public/.*
    static_dir: public
  - url: /static/.*
    static_dir: static
